Traceback (most recent call last):
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 622, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 85, in ensure_async
    result = await obj
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/jupyter_client/asynchronous/channels.py", line 48, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/gslee/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 841, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 646, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 696, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['from random import randint  # 모듈 불러오기를 맨 먼저 실행', '', 'print("비밀의 수 추측 게임에 환영합니다.")', '', 'secret = randint(1,100)     # 1부터 100까지의 수 중에서 무작위로 선택']
...
['            print("너무 작아요!")', '    except:', '        print("정수를 입력하세요.")', '', 'print("게임 종료!")']
-------------------

