Traceback (most recent call last):
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/gslee/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
f1 = Fraction(1, 4)
f2 = Fraction(1, 2)
f3 = f1 + f2
print(f3)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/tmp/ipykernel_3060/4216153219.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mf1[0m [0;34m=[0m [0mFraction[0m[0;34m([0m[0;36m1[0m[0;34m,[0m [0;36m4[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0mf2[0m [0;34m=[0m [0mFraction[0m[0;34m([0m[0;36m1[0m[0;34m,[0m [0;36m2[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0mf3[0m [0;34m=[0m [0mf1[0m [0;34m+[0m [0mf2[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0mprint[0m[0;34m([0m[0mf3[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/tmp/ipykernel_3060/499535648.py[0m in [0;36m__add__[0;34m(self, other_fraction)[0m
[1;32m     14[0m [0;34m[0m[0m
[1;32m     15[0m     [0;32mdef[0m [0m__add__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mother_fraction[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 16[0;31m         [0mnew_num[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mtop[0m [0;34m*[0m [0mother_fraction[0m[0;34m.[0m[0mden[0m [0;34m+[0m[0;31m [0m[0;31m\[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     17[0m                      [0mself[0m[0;34m.[0m[0mbottom[0m [0;34m*[0m [0mother_fraction[0m[0;34m.[0m[0mnum[0m[0;34m[0m[0;34m[0m[0m
[1;32m     18[0m         [0mnew_den[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mbottom[0m [0;34m*[0m [0mother_fraction[0m[0;34m.[0m[0mden[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: 'Fraction' object has no attribute 'den'
AttributeError: 'Fraction' object has no attribute 'den'

